spring.application.name=blog

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/blog-fastcampus
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# turn of auto migrating
spring.flyway.enabled=false
flyway.url=jdbc:mysql://localhost:3306/blog-fastcampus
flyway.user=${FLYWAY_USERNAME}
flyway.password=${FLYWAY_PASSWORD}

# spring security basic
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}